INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-01', '김치볶음밥', '북엇국', '비프 브루기뇽');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-02', '아란치니', '해물순두부찌개', '돈부리');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-03', '비트 수프', '오코노미야키', '크림 바질 피자');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-04', '닭강정', '삼계탕', '참치 샌드위치');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-05', '가이센동', '육개장', '감자튀김');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-06', '마라탕', '오징어볶음', '김치볶음밥');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-07', '마파두부밥', '김치찌개', '');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-08', '떡만두국', '사천식 돼지고기 볶음', '카츠돈');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-09', '김치볶음면', '곰탕', '연어 파스타');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-10', '곱창볶음', '해물된장찌개', '고추장찌개');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-11', '크로크무슈', '트러플 리소토', '');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-12', '참치 샌드위치', '감자탕', '부대찌개');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-13', '비빔국수', '돼지고기묵은지찜', '스테이크');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-14', '미트로프', '삼합', '된장찌개');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-15', '오코노미야키', '유부 초밥', '버섯국');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-16', '치즈 계란말이', '스윗 칠리 새우', '육개장');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-18', '멸치 김밥', '파전', '바질페스토 라비올리');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-19', '아스파라거스 수프', '불고기 타코', '치킨 시저랩');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-20', '돼지고기볶음', '양파 링', '크림 바질 피자');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-23', '감바스 리조또', '김치볶음면', '해물라면');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-24', '바질 페스토 샌드위치', '사골국', '갈릭 새우 파스타');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-25', '타코야키', '브로콜리 샐러드', '된장찌개');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-26', '고추참치 김밥', '라면', '양송이 수프');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-27', '김치볶음밥', '삼겹살','');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-28', '피자 토스트', '포테이토베이컨 피자', '베이컨 감자 샐러드');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-29', '', '명란 크림파스타', '크림 바질 피자');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-30', '닭갈비', '갈릭 토스트', '푸아그라');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-10-31', '짬짜면', '까르보나라 파스타', '김치찌개');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-01', '', '닭볶음탕', '포크 롤');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-02', '크림통새우', '베이글 샌드위치', '');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-03', '고로케', '', '새우 크림 리조또');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-04', '오삼불고기', '소고기덮밥', '매운 돼지갈비');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-05', '카레라이스', '낙지볶음', '');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-06', '야채 김밥', '김치찌개', '해물탕');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-07', '', '크림치즈 파스타', '라볶이');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-08', '굴밥', '버섯 리소토', '미역국');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-09', '파스타', '순대국', '돼지갈비');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-10', '오렌지 치킨', '사천식 양꼬치', '파김치장어전골');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-11', '감자탕', '카마메시', '해물 수제비');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-12', '미소시루', '갈비구이', '로코모코');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-13', '김치볶음밥', '버팔로 치킨 샌드위치', '호박 수프');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-14', '스테이크 타르타르', '우거지국', '트러플 감자튀김');
INSERT INTO Calendar (user_id, save_date, breakfast, lunch, dinner) VALUES ('1@naver.com', '2024-11-15', '베지터블 라자냐', '아보카도 토스트', '피쉬 앤 칩스');
