INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (1, '임연수구이', '장어정식', '어묵볶음', '2024-01-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (2, '파전', '포테이토 샐러드', '푸아그라', '2024-01-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (3, '스테이크 타르타르', '깐쇼새우', '굴밥', '2024-01-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (4, '어묵볶음', '불고기 타코', '마라양념탕수육', '2024-01-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (5, '파삼겹', '미트로프', '짬짜면', '2024-01-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (6, '곤약조림', '토마토 브루스케타', '소바', '2024-01-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (7, '감자채볶음', '감자전', '닭봉구이', '2024-01-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (8, '햄버거', '파파야 샐러드', '삼선짬뽕밥', '2024-01-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (9, '해물라면', '샐러드', '순대국밥', '2024-01-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (10, '떡갈비', '명란 크림파스타', '사천식 양꼬치', '2024-01-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (11, '황태국', '깻잎 김밥', '도미구이', '2024-01-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (12, '비지찌개', '포크 롤', '중화비빔면', '2024-01-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (13, '깻잎전', '계란말이', '낙지국', '2024-01-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (14, '시메사바', '연어구이', '비프 타르타르', '2024-01-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (15, '해물볶음우동', '설렁탕', '육개장', '2024-01-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (16, '사천식 돼지고기 볶음', '감자탕', '계란찜', '2024-01-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (17, '로코모코', '양고기 스테이크', '치즈버거', '2024-01-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (18, '오징어순대', '광어 사시미', '햄 치즈 토스트', '2024-01-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (19, '감자그라탕', '사골국', '불고기', '2024-01-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (20, '닭가슴살 스테이크', '아귀찜', '파파야 샐러드', '2024-01-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (21, '유린기', '치즈버거', '렌틸콩 샐러드', '2024-01-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (22, '오리엔탈 드레싱 샐러드', '갈비찜', '전어구이', '2024-01-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (23, '시금치나물', '고추짬뽕', '미역국', '2024-01-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (24, '치킨 크림파스타', '감자전', '미트로프', '2024-01-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (25, '전어구이', '히레카츠', '고추기름 닭고기', '2024-01-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (26, '우렁강된장', '김치전', '제육볶음', '2024-01-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (27, '햄 치즈 토스트', '크림수프', '오렌지 치킨', '2024-01-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (28, '피자 토스트', '짬짜면', '짜장면', '2024-01-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (29, '크림 시금치 파스타', '닭봉구이', '물막국수', '2024-01-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (30, '감자 샐러드', '두부전골', '짜장면', '2024-01-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (31, '양꼬치', '마파두부', '가라아게가츠동', '2024-01-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (32, '물김치', '돈카츠 회오리 오므라이스', '양꼬치', '2024-02-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (33, '된장찌개', '감자그라탕', '삼합', '2024-02-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (34, '닭볶음탕', '치즈 옥수수', '육회', '2024-02-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (35, '쌀국수', '홍합찜', '북경오리', '2024-02-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (36, '무생채', '브리또', '김치볶음밥', '2024-02-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (37, '도라지무침', '우엉조림', '볶음밥', '2024-02-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (38, '부대찌개', '참치 비빔밥', '우동', '2024-02-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (39, '고추장찌개', '짜장밥', '샐러드 피자', '2024-02-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (40, '참치국', '바질소바', '트러플 파스타', '2024-02-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (41, '타이 그린 카레', '치킨 너겟', '삼선짬뽕밥', '2024-02-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (42, '크림 치즈 베이글', '토마토 리소토', '애호박찌개', '2024-02-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (43, '우나기', '오이무침', '초벌 막창', '2024-02-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (44, '랍스터 비스크', '베지터블 라자냐', '참치 비빔밥', '2024-02-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (45, '콩비지찌개', '불닭', '우엉조림', '2024-02-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (46, '카마메시', '시래기된장국', '타코', '2024-02-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (47, '김치볶음밥', '전어구이', '렌틸콩 샐러드', '2024-02-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (48, '사천식 양꼬치', '부타동', '오징어볶음', '2024-02-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (49, '브로콜리 샐러드', '아란치니', '덴푸라', '2024-02-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (50, '감자채볶음', '북경오리', '샤케동', '2024-02-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (51, '샌드위치', '닭볶음탕', '쉬림프 타코', '2024-02-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (52, '비빔냉면', '붕장어구이', '오향장육', '2024-02-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (53, '크림 스프', '살몬 크림 파스타', '갈릭 토스트', '2024-02-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (54, '조기구이', '시래기된장국', '연어 김밥', '2024-02-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (55, '돼지갈비', '시메사바', '콩나물국', '2024-02-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (56, '바베큐 치킨 피자', '연어 타르타르', '허니 버터 칩', '2024-02-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (57, '꽁치조림', '떡국', '가자미조림', '2024-02-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (58, '참치 니스와 샐러드', '볶음밥', '양송이 크림파스타', '2024-02-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (59, '호박 수프', '무국', '고추짬뽕', '2024-02-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (60, '닭칼국수', '오이무침', '차돌박이 된장찌개', '2024-02-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (61, '사천식 양꼬치', '타이 새우 볶음', '크로와상 샌드위치', '2024-03-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (62, '수박 샐러드', '배추겉절이', '바질 페스토 샌드위치', '2024-03-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (63, '낙지볶음', '고등어구이', '삼선짬뽕밥', '2024-03-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (64, '황태찌개', '치즈계란말이', '버섯전골', '2024-03-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (65, '코코넛 쉬림프', '볶음밥', '크림 시금치 파스타', '2024-03-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (66, '미소 된장국', '오니기리', '니쿠자가', '2024-03-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (67, '짬뽕', '이카메시', '훈툰', '2024-03-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (68, '소대창', '불닭', '미역무침', '2024-03-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (69, '로메인 샐러드', '닭백숙', '미트볼 파스타', '2024-03-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (70, '도미구이', '곱창볶음', '버섯국', '2024-03-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (71, '가이센동', '토마토 바질 스프', '크림파스타', '2024-03-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (72, '아스파라거스 수프', '사천식 돼지고기 볶음', '소대창', '2024-03-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (73, '크림 스프', '청국장', '호박 수프', '2024-03-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (74, '잔치국수', '조개찜', '와플 샌드위치', '2024-03-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (75, '가마솥밥', '샐러드', '페스토 샌드위치', '2024-03-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (76, '바베큐 치킨', '바질페스토 파스타', '브로콜리 체다 수프', '2024-03-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (77, '크림 시금치 파스타', '육개장', '시저 치킨랩', '2024-03-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (78, '아보카도 토스트', '에비텐동', '감자탕', '2024-03-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (79, '라자냐', '도미구이', '새우 크림 리조또', '2024-03-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (80, '꿔바로우 샐러드', '아귀찜', '소막창', '2024-03-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (81, '참치볶음밥', '산적', '이카메시', '2024-03-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (82, '동파육', '치즈 퀘사디아', '육개장', '2024-03-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (83, '칼국수', '비트 수프', '찜닭', '2024-03-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (84, '갈치조림', '미소 된장국', '찜닭', '2024-03-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (85, '부대찌개', '바나나 브레드', '순두부찌개', '2024-03-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (86, '꽃목살', '떡국', '타코야키', '2024-03-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (87, '두부전골', '우동', '팥죽', '2024-03-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (88, '마라샹궈', '새우튀김', '제육덮밥', '2024-03-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (89, '채소전', '애플파이', '고구마튀김', '2024-03-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (90, '텐동', '미트로프', '소고기덮밥', '2024-03-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (91, '클럽 샌드위치', '소고기 김밥', '새우가츠동', '2024-03-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (92, '살몬 크림 파스타', '새우 토스트', '삼치구이', '2024-04-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (93, '새우 카레라이스', '새우 카레라이스', '시메사바', '2024-04-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (94, '갈치구이', '가라아게가츠동', '렌틸콩 샐러드', '2024-04-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (95, '명태구이', '튀김만두', '고구마치즈카츠', '2024-04-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (96, '살사 치킨 타코', '프렌치 토스트', '백숙', '2024-04-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (97, '크림수프', '김치전', '닭가슴살 튀김', '2024-04-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (98, '소이 글레이즈드 연어', '바베큐 폭립', '동파육', '2024-04-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (99, '날치알 김밥', '양갈비', '황태해장국', '2024-04-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (100, '토마호크 스테이크', '야채튀김', '우렁강된장', '2024-04-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (101, '크림치즈 베이글', '크림치즈 파스타', '새우젓 무침', '2024-04-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (102, '크림통새우', '타코', '광어 사시미', '2024-04-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (103, '갈치조림', '감자 샐러드', '연어 타르타르', '2024-04-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (104, '비트 샐러드', '오징어볶음', '냉채족발', '2024-04-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (105, '탕수육', '유니짜장', '고등어구이', '2024-04-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (106, '샌드위치', '대파무침', '해물덮밥', '2024-04-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (107, '크림치즈 파스타', '오징어볶음', '소갈비살', '2024-04-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (108, '카츠돈', '새우볶음밥', '애플 크럼블', '2024-04-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (109, '매운탕', '양송이 수프', '전복죽', '2024-04-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (110, '갈릭 새우 파스타', '매운 갈비찜 찌개', '가자미구이', '2024-04-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (111, '브리또 볼', '매운 갈비찜 찌개', '파김치장어전골', '2024-04-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (112, '파스타', '갈릭 토스트', '무생채', '2024-04-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (113, '참치국', '도미구이', '참치 사시미', '2024-04-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (114, '감바스 알 아히요', '바질 페스토 샌드위치', '샤케동', '2024-04-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (115, '김치국', '토마호크 스테이크', '배추국', '2024-04-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (116, '장어정식', '오삼불고기', '치킨 카레', '2024-04-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (117, '명태구이', '토마토 치즈 타르트', '새우 카레라이스', '2024-04-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (118, '참치 비빔밥', '가이센동', '순대', '2024-04-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (119, '맥 앤 치즈', '철판 볶음밥', '오니기리', '2024-04-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (120, '애플 크럼블', '랍스터 비스크', '보리밥', '2024-04-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (121, '깐쇼새우덮밥', '라조기', '버팔로 치킨 샐러드', '2024-04-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (122, '유린기', '고등어구이', '닭가슴살 스테이크', '2024-05-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (123, '가츠샌드', '닭백숙', '치킨 너겟', '2024-05-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (124, '굴전', '토마토 바질 스프', '바질페스토 파스타', '2024-05-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (125, '베이컨 김밥', '도토리묵무침', '오렌지 치킨', '2024-05-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (126, '삼치구이', '베이컨 에그 베네딕트', '애호박 라자냐', '2024-05-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (127, '새우구이', '소막창', '호박 수프', '2024-05-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (128, '백숙', '마파두부', '새우 크림 리조또', '2024-05-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (129, '푸실리 파스타', '라볶이', '미트볼 파스타', '2024-05-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (130, '브런치 세트', '덴푸라', '클럽 샌드위치', '2024-05-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (131, '볶음밥', '규카츠', '로메인 샐러드', '2024-05-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (132, '토마토 수프', '파스타', '교카이라멘', '2024-05-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (133, '해물 수제비', '멘보샤', '오향장육', '2024-05-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (134, '오니기리', '피자', '버팔로 치킨 샐러드', '2024-05-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (135, '조개찜', '양송이 수프', '감바스 알 아히요', '2024-05-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (136, '꼬막비빔밥', '오렌지 치킨', '김치볶음면', '2024-05-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (137, '장어정식', '허니 버터 칩', '안동찜닭', '2024-05-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (138, '불고기', '아란치니', '연어 스테이크', '2024-05-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (139, '모듬카츠', '장어덮밥', '초계국수', '2024-05-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (140, '배추국', '라멘', '카마메시', '2024-05-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (141, '소곱창', '스테이크', '브루스케타', '2024-05-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (142, '우동', '치킨 크림파스타', '양송이 수프', '2024-05-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (143, '매운돼지갈비', '새우 스캄피 파스타', '피쉬 앤 칩스', '2024-05-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (144, '새우 토스트', '오리 로스트', '비프 브루기뇽', '2024-05-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (145, '해물덮밥', '카레', '규카츠', '2024-05-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (146, '라멘', '버팔로 치킨 샌드위치', '크림파스타', '2024-05-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (147, '파삼겹', '매운 갈비찜 찌개', '치즈 퀘사디아', '2024-05-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (148, '초밥', '김치볶음밥', '호박 수프', '2024-05-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (149, '오야코동', '쫄면', '소바', '2024-05-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (150, '전복죽', '바질페스토 피자', '랍스터 롤', '2024-05-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (151, '애호박 라자냐', '참치국', '프렌치 어니언 수프', '2024-05-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (152, '돼지갈비 스튜', '고등어구이', '파스타', '2024-05-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (153, '닭백숙', '새우가츠동', '크림파스타', '2024-06-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (154, '계란말이', '튀김만두', '부리또', '2024-06-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (155, '해물순두부찌개', '삼선짬뽕밥', '소이 글레이즈드 연어', '2024-06-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (156, '해물 수제비', '메밀국수 샐러드', '마파두부', '2024-06-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (157, '짜장밥', '고추참치 김밥', '로스카츠', '2024-06-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (158, '가지나물', '청국장', '초밥', '2024-06-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (159, '사과 소스 포크', '마라짬뽕', '명태구이', '2024-06-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (160, '만두국', '고등어구이', '갈비찜', '2024-06-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (161, '시메사바', '떡볶이', '우렁강된장', '2024-06-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (162, '마파두부', '메밀국수 샐러드', '아란치니', '2024-06-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (163, '매운 갈비찜 찌개', '계란 김밥', '비스크 수프', '2024-06-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (164, '닭갈비 덮밥', '물김치', '토마토 바질 스프', '2024-06-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (165, '카츠돈', '랍스터 롤', '대파무침', '2024-06-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (166, '토마토 갈릭 파스타', '오삼불고기', '참치 니스와 샐러드', '2024-06-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (167, '크로와상 샌드위치', '떡갈비', '깐풍기', '2024-06-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (168, '멍게무침', '연어 스테이크', '치즈 퀘사디아', '2024-06-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (169, '카츠돈', '낙지볶음', '오차즈케', '2024-06-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (170, '토마토 모차렐라 피자', '전복죽', '고구마전', '2024-06-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (171, '포크 롤', '불닭볶음면', '계란찜', '2024-06-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (172, '동파육', '소막창', '토마토 리소토', '2024-06-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (173, '붕장어구이', '퀘사디아', '베지터블 라자냐', '2024-06-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (174, '미트볼 파스타', '감자튀김', '삼선짬뽕밥', '2024-06-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (175, '레몬 허니 샐러드', '한우구이', '트러플 파스타', '2024-06-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (176, '고추짬뽕', '갈치조림', '소시지 그라탱', '2024-06-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (177, '굴전', '살사 치킨 타코', '닭가슴살 튀김', '2024-06-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (178, '우엉조림', '볶음밥', '크림 스프', '2024-06-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (179, '렌틸콩 샐러드', '바베큐 치킨 피자', '트러플 파스타', '2024-06-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (180, '깐쇼새우', '오징어국', '해물볶음우동', '2024-06-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (181, '짬짜면', '방어구이', '바베큐 폭립', '2024-06-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (182, '도라지무침', '동태찌개', '낙지탕탕이', '2024-06-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (183, '오향장육', '닭갈비', '백합탕', '2024-07-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (184, '그릴드 치즈 샌드위치', '치즈카츠', '낙지전골', '2024-07-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (185, '잡채밥', '시래기국', '무채 비빔국수', '2024-07-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (186, '불닭', '오리엔탈 드레싱 샐러드', '연어 스테이크', '2024-07-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (187, '로코모코', '크로크무슈', '시금치 수프', '2024-07-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (188, '무채 비빔국수', '야채 김밥', '파삼겹', '2024-07-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (189, '떡만두국', '할라피뇨 팝퍼', '짬짜면', '2024-07-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (190, '닭볶음탕', '파삼겹', '치즈 감자튀김', '2024-07-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (191, '시저 치킨랩', '상하이볶음면', '차돌박이 된장찌개', '2024-07-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (192, '페스토 샌드위치', '고구마치즈카츠', '돈코츠라멘', '2024-07-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (193, '버섯 볶음밥', '차돌박이 된장찌개', '퀘사디아', '2024-07-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (194, '닭다리 구이', '잡채', '불고기 덮밥', '2024-07-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (195, '임연수구이', '블랙 올리브 파스타', '불고기 타코', '2024-07-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (196, '어묵탕', '제육덮밥', '무채 비빔국수', '2024-07-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (197, '장어구이', '로스카츠', '디아블로 피자', '2024-07-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (198, '순두부찌개', '닭갈비', '애플파이', '2024-07-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (199, '칠리 치즈 감자튀김', '안동찜닭', '해물된장찌개', '2024-07-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (200, '베이컨 감자 샐러드', '순대', '카마메시', '2024-07-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (201, '사우전 아일랜드 샐러드', '불닭볶음면', '우거지국', '2024-07-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (202, '멘보샤', '해물파전', '라임 치킨', '2024-07-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (203, '스테이크 타르타르', '레몬 허니 샐러드', '그릴드 연어', '2024-07-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (204, '시나몬 롤', '명란 크림파스타', '샤케동', '2024-07-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (205, '유산슬', '토마토 리소토', '청국장', '2024-07-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (206, '미소 된장국', '포테이토베이컨 피자', '버팔로 치킨 샌드위치', '2024-07-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (207, '새우볶음밥', '굴밥', '매콤로제파스타', '2024-07-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (208, '해물라면', '장어덮밥', '해물파전', '2024-07-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (209, '떡볶이', '오징어순대', '사우전 아일랜드 샐러드', '2024-07-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (210, '해물파전', '브런치 세트', '우렁강된장', '2024-07-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (211, '새우 크림 리소토', '시저 샐러드', '소시지 그라탱', '2024-07-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (212, '장어구이', '애호박 라자냐', '파전', '2024-07-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (213, '물냉면', '제육볶음', '알리오 올리오', '2024-07-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (214, '돈부리', '덴푸라', '미역국', '2024-08-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (215, '카레라이스', '시금치 수프', '랍스터 크림 스프', '2024-08-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (216, '트러플 파스타', '오코노미야키', '미소 된장국', '2024-08-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (217, '나가사키 짬뽕', '로스카츠', '양파 링', '2024-08-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (218, '연어 타르타르', '치즈계란말이', '오이 샐러드', '2024-08-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (219, '마파두부밥', '순두부국', '북경오리', '2024-08-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (220, '참치 샌드위치', '파스타', '해물탕', '2024-08-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (221, '날치알 김밥', '포테이토 샐러드', '살몬 크림 파스타', '2024-08-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (222, '바베큐 치킨', '굴밥', '치즈스틱', '2024-08-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (223, '참치국', '새우 크림 리소토', '파삼겹', '2024-08-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (224, '생채', '치즈 감자튀김', '우렁강된장', '2024-08-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (225, '크로켓', '조개찜', '연어 샐러드', '2024-08-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (226, '도미구이', '감바스 리조또', '토마호크 스테이크', '2024-08-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (227, '쉬림프 타코', '덴푸라', '바베큐 치킨 피자', '2024-08-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (228, '미역무침', '닭갈비 덮밥', '시래기국', '2024-08-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (229, '소룡포', '콩국수', '곱창전골', '2024-08-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (230, '연어 사시미', '차슈 라멘', '에그 베네딕트', '2024-08-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (231, '우럭매운탕', '토마토 갈릭 파스타', '사천식 양꼬치', '2024-08-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (232, '스테이크 타르타르', '야채튀김', '호박전', '2024-08-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (233, '깐풍기', '연어 타르타르', '가라아게가츠동', '2024-08-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (234, '토마호크 스테이크', '연어 샌드위치', '깻잎 김밥', '2024-08-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (235, '어묵탕', '까르보나라 파스타', '게장', '2024-08-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (236, '미나리무침', '오이 샐러드', '청포묵', '2024-08-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (237, '로스카츠', '시저 샐러드', '제육덮밥', '2024-08-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (238, '토마토 갈릭 파스타', '해물볶음우동', '시나몬 롤', '2024-08-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (239, '타마고야키', '오리엔탈 드레싱 샐러드', '우렁 된장찌개', '2024-08-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (240, '항정살', '중화비빔면', '베이글 샌드위치', '2024-08-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (241, '새우 크림 리조또', '두부김치', '이카메시', '2024-08-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (242, '유부 김밥', '채소전', '피자 토스트', '2024-08-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (243, '고추기름 닭고기', '허니 버터 칩', '와플 샌드위치', '2024-08-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (244, '닭백숙', '불닭', '시금치 피자', '2024-08-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (245, '브런치 세트', '낙지탕탕이', '고추장찌개', '2024-09-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (246, '새우 토스트', '계란말이', '오리 로스트', '2024-09-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (247, '스윗 칠리 새우', '블랙빈 수프', '연어 스테이크', '2024-09-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (248, '클램 차우더', '새우 스캄피 파스타', '군만두', '2024-09-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (249, '샌드위치', '가츠샌드', '깐쇼새우덮밥', '2024-09-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (250, '토마토 바질 스프', '샐러드롤', '레몬 허니 샐러드', '2024-09-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (251, '조기구이', '양꼬치', '오징어국', '2024-09-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (252, '갈치구이', '클램 차우더', '크림수프', '2024-09-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (253, '훈툰', '초계비빔국수', '갈비구이', '2024-09-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (254, '차슈 라멘', '한우구이', '해물순두부찌개', '2024-09-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (255, '타마고야키', '호박전', '초계비빔국수', '2024-09-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (256, '오코노미야키', '감자전', '레몬 허니 샐러드', '2024-09-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (257, '가츠동', '가마솥밥', '회냉면', '2024-09-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (258, '치즈 옥수수', '꿔바로우', '마파면', '2024-09-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (259, '파삼겹', '랍스터 크림 스프', '아스파라거스 수프', '2024-09-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (260, '토마토 바질 스프', '해물된장찌개', '규동', '2024-09-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (261, '유린기', '타이 그린 카레', '소대창', '2024-09-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (262, '해물 수제비', '호박전', '깐쇼새우덮밥', '2024-09-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (263, '파전', '레몬 치킨', '고추참치 김밥', '2024-09-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (264, '야채 김밥', '순대국밥', '브리또', '2024-09-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (265, '소갈비찜', '수박 샐러드', '감자전', '2024-09-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (266, '조개찜', '수박 샐러드', '참치국', '2024-09-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (267, '조개찜', '스테이크', '육개장', '2024-09-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (268, '라볶이', '부대찌개', '꽃목살', '2024-09-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (269, '라조기', '참치 김밥', '우엉조림', '2024-09-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (270, '게장', '치킨 시저랩', '감자탕', '2024-09-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (271, '파인애플 볶음밥', '우럭매운탕', '명태구이', '2024-09-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (272, '포크 롤', '애호박찌개', '굴밥', '2024-09-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (273, '굴밥', '북엇국', '버섯전골', '2024-09-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (274, '치킨 필라프', '해물덮밥', '깻잎 김밥', '2024-09-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (275, '우렁 된장찌개', '산적', '버섯국', '2024-10-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (276, '멍게무침', '살몬 아보카도 샐러드', '상하이볶음면', '2024-10-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (277, '치즈버거', '참치 사시미', '맥 앤 치즈', '2024-10-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (278, '타이 새우 볶음', '아스파라거스 수프', '양파 링', '2024-10-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (279, '새우완자', '사천식 양꼬치', '치킨 필라프', '2024-10-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (280, '코코넛 쉬림프', '애플 크럼블', '우나기', '2024-10-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (281, '안동찜닭', '참치 샌드위치', '방어구이', '2024-10-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (282, '소불고기', '크림치즈 파스타', '탕수육', '2024-10-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (283, '돈카츠 회오리 오므라이스', '고구마치즈카츠', '타코', '2024-10-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (284, '해물라면', '탄탄멘', '바질 페스토 샌드위치', '2024-10-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (285, '김치볶음면', '참치마요덮밥', '참치볶음밥', '2024-10-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (286, '버섯 볶음밥', '떡만두국', '콩나물무침', '2024-10-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (287, '돼지고기볶음', '시래기국', '사천식 돼지고기 볶음', '2024-10-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (288, '코코넛 쉬림프', '치즈카츠', '타마고야키', '2024-10-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (289, '한우구이', '삼치구이', '멘보샤', '2024-10-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (290, '크림 치즈 베이글', '비빔국수', '가라아게', '2024-10-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (291, '퀘사디아', '치킨 팟파이', '계란국', '2024-10-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (292, '채소전', '꼬막비빔밥', '감자 피자', '2024-10-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (293, '사우전 아일랜드 샐러드', '사천식 양꼬치', '두부조림', '2024-10-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (294, '월남쌈', '순두부찌개', '무생채', '2024-10-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (295, '감자채볶음', '그릴드 치즈 샌드위치', '팥죽', '2024-10-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (296, '초계국수', '오니기리', '할라피뇨 팝퍼', '2024-10-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (297, '베이컨 에그 베네딕트', '수박 샐러드', '샐러드롤', '2024-10-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (298, '찐빵', '마라탕', '살사 치킨 타코', '2024-10-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (299, '체다 치즈 튀김', '깻잎전', '호박 수프', '2024-10-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (300, '멘보샤', '햄 치즈 토스트', '가자미조림', '2024-10-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (301, '토마토 치즈 타르트', '오차즈케', '마라샹궈', '2024-10-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (302, '매운돼지갈비', '홍합탕', '가라아게가츠동', '2024-10-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (303, '연어구이', '깻잎전', '깐쇼새우', '2024-10-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (304, '크로켓', '치즈 퀘사디아', '치킨 크림파스타', '2024-10-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (305, '고추짬뽕', '도라지무침', '사과 소스 포크', '2024-10-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (306, '계란국', '랍스터 비스크', '연어 사시미', '2024-11-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (307, '살몬 아보카도 샐러드', '낙지탕탕이', '소갈비살', '2024-11-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (308, '연어 김밥', '살몬 크림 파스타', '고구마튀김', '2024-11-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (309, '포테이토 샐러드', '매운 갈비찜 찌개', '포테이토 샐러드', '2024-11-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (310, '새우가츠동', '페스토 샌드위치', '마라샹궈', '2024-11-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (311, '광어 사시미', '소이 글레이즈드 연어', '순대국', '2024-11-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (312, '살몬 크림 파스타', '잡채', '찜닭', '2024-11-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (313, '체다 치즈 튀김', '파파야 샐러드', '곰탕', '2024-11-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (314, '바지락 칼국수', '부추전', '족발', '2024-11-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (315, '브로콜리 체다 수프', '파파야 샐러드', '잡채밥', '2024-11-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (316, '우나기', '곰탕', '감자찌개', '2024-11-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (317, '붕장어구이', '규동', '임연수구이', '2024-11-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (318, '할라피뇨 팝퍼', '마라짬뽕', '튀김만두', '2024-11-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (319, '아란치니', '아보카도 토스트', '닭가슴살 샐러드', '2024-11-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (320, '스테이크 타르타르', '오이무침', '유부 초밥', '2024-11-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (321, '광어 사시미', '치즈스틱', '가이센동', '2024-11-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (322, '프레즐', '마라탕', '알리오 올리오', '2024-11-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (323, '오차즈케', '미역무침', '비빔국수', '2024-11-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (324, '스테이크', '미트볼 파스타', '마르게리타 피자', '2024-11-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (325, '닭다리 구이', '설렁탕', '초벌 막창', '2024-11-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (326, '양파 링', '깐쇼새우', '상하이볶음면', '2024-11-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (327, '로메인 샐러드', '낙지탕탕이', '돈코츠라멘', '2024-11-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (328, '알리오 올리오', '연어 파스타', '로코모코', '2024-11-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (329, '트러플 리소토', '버섯볶음', '오코노미야키', '2024-11-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (330, '브로콜리 샐러드', '크림치즈 베이글', '랍스터 롤', '2024-11-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (331, '우럭매운탕', '소룡포', '타코야키', '2024-11-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (332, '브루스케타', '청포묵', '해물탕', '2024-11-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (333, '돼지고기묵은지찜', '오렌지 치킨', '아란치니', '2024-11-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (334, '고추짬뽕', '비트 샐러드', '닭칼국수', '2024-11-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (335, '돈가스 김밥', '쌀국수', '연어 샌드위치', '2024-11-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (336, '라멘', '볶음밥', '이카메시', '2024-12-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (337, '오니기리', '계란국', '군만두', '2024-12-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (338, '토마토 수프', '생채', '순두부국', '2024-12-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (339, '매운돼지갈비', '매운 갈비찜 찌개', '타이 그린 카레', '2024-12-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (340, '토마토 치즈 타르트', '마늘빵', '된장찌개', '2024-12-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (341, '순두부국', '카츠돈', '맥 앤 치즈', '2024-12-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (342, '꽃목살', '브리또', '초벌 막창', '2024-12-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (343, '북경오리', '수박 샐러드', '수박 샐러드', '2024-12-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (344, '양파 링', '삼치구이', '오징어 튀김', '2024-12-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (345, '회냉면', '방어구이', '비빔냉면', '2024-12-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (346, '야끼소바', '고추기름 닭고기', '가자미구이', '2024-12-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (347, '체다 감자 크림', '참치국', '미역국', '2024-12-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (348, '꼬막비빔밥', '오징어볶음', '버섯전골', '2024-12-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (349, '숙성지 김치찌개', '훈툰', '크로와상 샌드위치', '2024-12-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (350, '임연수구이', '후라이드 치킨', '치킨 팟파이', '2024-12-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (351, '감자채볶음', '굴전', '튀김우동', '2024-12-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (352, '크림파스타', '가츠동', '고등어조림', '2024-12-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (353, '우동', '회냉면', '오징어국', '2024-12-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (354, '시메사바', '크림파스타', '비지찌개', '2024-12-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (355, '새우 크림 리소토', '유부 김밥', '프레즐', '2024-12-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (356, '참치 사시미', '초밥', '베지터블 라자냐', '2024-12-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (357, '우나기', '굴밥', '꽁치구이', '2024-12-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (358, '닭튀김', '치킨 파마산', '전주비빔밥', '2024-12-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (359, '치킨 시저랩', '떡만두국', '코코넛 쉬림프', '2024-12-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (360, '에그 베네딕트', '부타동', '육개장', '2024-12-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (361, '로스카츠', '장어정식', '라자냐', '2024-12-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (362, '새우젓 무침', '해물찜', '삼선짬뽕밥', '2024-12-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (363, '브로콜리 샐러드', '생채', '치킨 알프레도', '2024-12-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (364, '렌틸콩 샐러드', '연어 김밥', '오향장육', '2024-12-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (365, '오삼불고기', '백합탕', '페스토 샌드위치', '2024-12-30');
