INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (1, '로스카츠', '소고기 김밥', '허니 버터 칩', '2024-01-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (2, '잔치국수', '치킨 너겟', '살몬 아보카도 샐러드', '2024-01-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (3, '계란말이', '바질 페스토 샌드위치', '백합탕', '2024-01-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (4, '가마솥밥', '양갈비', '감자탕', '2024-01-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (5, '치킨 필라프', '연어구이', '족발', '2024-01-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (6, '에그 베네딕트', '삼계탕', '블랙빈 수프', '2024-01-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (7, '베이글 샌드위치', '닭가슴살 스테이크', '참치 김밥', '2024-01-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (8, '열무김치', '새우구이', '붕장어구이', '2024-01-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (9, '북엇국', '매콤로제파스타', '베이컨 감자 샐러드', '2024-01-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (10, '할라피뇨 팝퍼', '꿔바로우', '삼치구이', '2024-01-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (11, '닭다리 구이', '매운탕', '김치찌개', '2024-01-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (12, '바지락 칼국수', '치킨 시저랩', '칠리 치즈 감자튀김', '2024-01-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (13, '체다 감자 크림', '물막국수', '맥 앤 치즈', '2024-01-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (14, '파파야 샐러드', '청포묵', '피자 토스트', '2024-01-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (15, '오징어 튀김', '파인애플 볶음밥', '쌀국수', '2024-01-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (16, '토마토 바질 스프', '마늘빵', '참치마요덮밥', '2024-01-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (17, '계란찜', '피쉬 앤 칩스', '크림수프', '2024-01-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (18, '갈릭 토스트', '고등어구이', '참치 니스와 샐러드', '2024-01-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (19, '감바스 알 아히요', '호박 수프', '소불고기', '2024-01-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (20, '유린기', '카라이라멘', '라자냐', '2024-01-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (21, '해물탕', '클럽 샌드위치', '초벌 막창', '2024-01-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (22, '갈릭 토스트', '김치볶음면', '체다 치즈 칩', '2024-01-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (23, '호박죽', '팥죽', '페퍼로니 피자', '2024-01-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (24, '포테이토베이컨 피자', '연어 사시미', '새우가츠동', '2024-01-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (25, '크림 시금치 파스타', '마라짬뽕', '연어 타르타르', '2024-01-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (26, '김치국', '감자 샐러드', '양송이 크림파스타', '2024-01-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (27, '토마토 모차렐라 피자', '날치알 김밥', '콩국수', '2024-01-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (28, '감자찌개', '토마토 바질 스프', '치즈 퀘사디아', '2024-01-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (29, '크림 바질 피자', '가라아게가츠동', '돈가스 김밥', '2024-01-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (30, '샐러드롤', '유니짜장', '양송이 크림파스타', '2024-01-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (31, '크로와상 샌드위치', '탄탄멘', '떡국', '2024-01-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (32, '콩국수', '감자크림수프', '초계국수', '2024-02-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (33, '갈비구이', '마파두부밥', '소룡포', '2024-02-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (34, '아스파라거스 수프', '시저 샐러드', '갈비구이', '2024-02-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (35, '할라피뇨 팝퍼', '닭갈비', '참치국', '2024-02-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (36, '우나기', '훈제 연어 샐러드', '차돌박이 된장찌개', '2024-02-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (37, '우렁강된장', '백합탕', '참치 니스와 샐러드', '2024-02-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (38, '버섯 리소토', '돈부리', '김치볶음면', '2024-02-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (39, '프렌치 어니언 수프', '카레', '브루스케타', '2024-02-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (40, '두부전골', '로메인 샐러드', '버팔로윙', '2024-02-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (41, '새우 토스트', '살몬 크림 파스타', '살몬 크림 파스타', '2024-02-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (42, '크림통새우', '시메사바', '참치국', '2024-02-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (43, '삼계탕', '깻잎전', '황태찌개', '2024-02-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (44, '멘보샤', '고추장찌개', '굴밥', '2024-02-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (45, '차슈 라멘', '렌틸콩 샐러드', '차돌박이 된장찌개', '2024-02-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (46, '사우전 아일랜드 샐러드', '아란치니', '오징어볶음', '2024-02-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (47, '돼지고기묵은지찜', '바질소바', '배추국', '2024-02-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (48, '참치 니스와 샐러드', '꽁치조림', '백숙', '2024-02-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (49, '와플 샌드위치', '물막국수', '비트 샐러드', '2024-02-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (50, '후라이드 치킨', '된장찌개', '카레라이스', '2024-02-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (51, '떡국', '햄버거', '소고기덮밥', '2024-02-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (52, '페퍼로니 피자', '갈비찜', '백숙', '2024-02-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (53, '클럽 샌드위치', '북경오리', '참치 김밥', '2024-02-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (54, '칠리 치즈 감자튀김', '돼지고기묵은지찜', '초계국수', '2024-02-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (55, '매운갈비찜', '콩국수', '김치볶음면', '2024-02-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (56, '마르게리타 피자', '닭볶음탕', '불고기', '2024-02-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (57, '두부조림', '청포묵', '고구마치즈카츠', '2024-02-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (58, '치킨 카레', '바질페스토 라비올리', '순대국', '2024-02-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (59, '라면', '냉채족발', '떡갈비', '2024-02-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (60, '사우전 아일랜드 샐러드', '닭가슴살 튀김', '양파 링', '2024-02-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (61, '고추짬뽕', '애호박전', '순대', '2024-03-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (62, '마라양념탕수육', '양고기 스테이크', '소고기덮밥', '2024-03-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (63, '푸아그라', '돈부리', '닭강정', '2024-03-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (64, '철판 볶음밥', '광어 사시미', '한우구이', '2024-03-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (65, '순대국', '깐쇼새우', '해물찜', '2024-03-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (66, '베이컨 김밥', '랍스터 비스크', '갈릭 새우 파스타', '2024-03-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (67, '타이 그린 카레', '우나기', '샤케동', '2024-03-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (68, '시래기국', '양갈비', '새우가츠동', '2024-03-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (69, '멸치 김밥', '멸치 김밥', '백합탕', '2024-03-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (70, '치즈계란말이', '마라양념탕수육', '유린기', '2024-03-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (71, '고구마치즈카츠', '포테이토베이컨 피자', '날치알 주먹밥', '2024-03-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (72, '곱창볶음', '베지터블 라자냐', '부대찌개', '2024-03-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (73, '임연수구이', '코코넛 치킨', '샐러드롤', '2024-03-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (74, '크림 시금치 파스타', '참치마요덮밥', '꽁치구이', '2024-03-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (75, '고추짬뽕', '감자 피자', '코코넛 치킨', '2024-03-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (76, '시저 파스타 샐러드', '닭볶음탕', '가이센동', '2024-03-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (77, '백숙', '소불고기', '오차즈케', '2024-03-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (78, '브런치 세트', '라따뚜이', '마파두부밥', '2024-03-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (79, '애호박찌개', '갈비탕', '비프 브루기뇽', '2024-03-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (80, '양송이 크림파스타', '카레라이스', '아귀찜', '2024-03-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (81, '탕수육', '가자미조림', '잡채밥', '2024-03-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (82, '닭볶음탕', '조개찜', '푸아그라', '2024-03-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (83, '버팔로윙', '초계비빔국수', '깻잎 김밥', '2024-03-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (84, '가츠샌드', '돼지고기묵은지찜', '튀김만두', '2024-03-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (85, '사과 소스 포크', '탄탄멘', '양송이 크림파스타', '2024-03-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (86, '그릴드 연어', '바나나 브레드', '피쉬 앤 칩스', '2024-03-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (87, '타이 그린 카레', '우렁강된장', '라면', '2024-03-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (88, '유린기', '불고기', '황태국', '2024-03-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (89, '이카메시', '임연수구이', '파김치장어전골', '2024-03-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (90, '한우구이', '크림치즈 베이글', '할라피뇨 팝퍼', '2024-03-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (91, '스윗 칠리 새우', '트로피컬 샐러드', '삼선짬뽕밥', '2024-03-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (92, '갈릭 새우 파스타', '소시지 그라탱', '해물 수제비', '2024-04-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (93, '고구마전', '임연수구이', '피자 토스트', '2024-04-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (94, '매운돼지갈비', '마라샹궈', '라멘', '2024-04-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (95, '파파야 샐러드', '유린기', '돼지갈비 스튜', '2024-04-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (96, '참치 샌드위치', '카츠돈', '바질 페스토 샌드위치', '2024-04-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (97, '가츠동', '불고기', '멸치 김밥', '2024-04-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (98, '찜닭', '호박 수프', '김치국', '2024-04-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (99, '수제비', '산적', '잔치국수', '2024-04-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (100, '시래기된장국', '할라피뇨 팝퍼', '할라피뇨 팝퍼', '2024-04-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (101, '페스토 샌드위치', '건두부볶음', '떡국', '2024-04-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (102, '햄버거', '회덮밥', '후라이드 치킨', '2024-04-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (103, '살몬 크림 파스타', '부추전', '갈치구이', '2024-04-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (104, '한우구이', '동파육', '교카이라멘', '2024-04-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (105, '숙성지 김치찌개', '고추참치 김밥', '참치 니스와 샐러드', '2024-04-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (106, '페스토 샌드위치', '이카메시', '오징어볶음', '2024-04-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (107, '브리또', '콩나물국', '브리또', '2024-04-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (108, '소갈비살', '푸아그라', '오니기리', '2024-04-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (109, '갈비찜', '가츠샌드', '조개찜', '2024-04-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (110, '철판 볶음밥', '와플 샌드위치', '불고기 타코', '2024-04-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (111, '오렌지 치킨', '사골국', '소갈비살', '2024-04-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (112, '물막국수', '한우구이', '두부조림', '2024-04-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (113, '사골국', '육회', '고추기름 닭고기', '2024-04-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (114, '갈비찜', '푸실리 파스타', '크로켓', '2024-04-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (115, '짜장밥', '연어 김밥', '새우 크림 리조또', '2024-04-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (116, '비지찌개', '트러플 리소토', '매운탕', '2024-04-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (117, '코코넛 치킨', '치킨 팟파이', '하이라이스', '2024-04-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (118, '오리 로스트', '모듬카츠', '타마고야키', '2024-04-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (119, '해물순두부찌개', '갈비찜', '어묵볶음', '2024-04-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (120, '부리또', '바질페스토 라비올리', '가마솥밥', '2024-04-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (121, '규동', '굴전', '팥죽', '2024-04-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (122, '가라아게', '연어 파스타', '건두부볶음', '2024-05-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (123, '탕수육', '감자튀김', '동태찌개', '2024-05-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (124, '짬짜면', '포테이토베이컨 피자', '비트 샐러드', '2024-05-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (125, '월남쌈', '쫄면', '새우 크림 리조또', '2024-05-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (126, '라조기', '불고기 타코', '콩국수', '2024-05-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (127, '살사 치킨 타코', '구운 감자 샐러드', '퀘사디아', '2024-05-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (128, '탄탄멘', '차돌박이 된장찌개', '와플 샌드위치', '2024-05-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (129, '닭다리 구이', '토마토 모차렐라 피자', '구운 감자 샐러드', '2024-05-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (130, '곱창전골', '치킨 시저랩', '건두부볶음', '2024-05-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (131, '배추국', '파전', '타코야키', '2024-05-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (132, '고등어조림', '회덮밥', '쫄면', '2024-05-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (133, '육회', '코코넛 치킨', '샤케동', '2024-05-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (134, '만두국', '양파 링', '아란치니', '2024-05-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (135, '마늘빵', '짜장밥', '군만두', '2024-05-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (136, '돈가스 김밥', '토마토 치즈 타르트', '스윗 칠리 새우', '2024-05-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (137, '북엇국', '히레카츠', '메밀국수 샐러드', '2024-05-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (138, '비프 타르타르', '소시지 그라탱', '쉬림프 타코', '2024-05-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (139, '브루스케타', '까르보나라 파스타', '클램 차우더', '2024-05-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (140, '구운 감자 샐러드', '차돌박이 된장찌개', '치즈계란말이', '2024-05-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (141, '비트 샐러드', '감자그라탕', '닭가슴살 스테이크', '2024-05-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (142, '미소시루', '떡만두국', '살몬 크림 파스타', '2024-05-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (143, '고추참치 김밥', '부추전', '바질페스토 라비올리', '2024-05-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (144, '안동찜닭', '치즈버거', '연어구이', '2024-05-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (145, '오향장육', '치즈 옥수수', '파인애플 볶음밥', '2024-05-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (146, '황태국', '햄버거', '육개장', '2024-05-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (147, '황태국', '고등어조림', '콩나물국', '2024-05-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (148, '피자', '매운돼지갈비', '파파야 샐러드', '2024-05-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (149, '짜장밥', '쭈꾸미볶음', '로스카츠', '2024-05-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (150, '채소전', '크림 바질 피자', '계란 김밥', '2024-05-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (151, '숙성지 김치찌개', '깐풍기', '스윗 칠리 새우', '2024-05-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (152, '낙지국', '투움바 파스타', '치즈 퀘사디아', '2024-05-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (153, '삼치구이', '야채튀김', '체다 치즈 튀김', '2024-06-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (154, '알리오 올리오', '푸실리 파스타', '양고기 찹스', '2024-06-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (155, '클램 차우더', '오렌지 치킨', '오리엔탈 드레싱 샐러드', '2024-06-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (156, '장어덮밥', '낙지전골', '튀김만두', '2024-06-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (157, '타이 그린 카레', '순대', '참치 샌드위치', '2024-06-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (158, '닭강정', '비건 버거', '바베큐 치킨 피자', '2024-06-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (159, '코코넛 치킨', '조개찜', '시저 파스타 샐러드', '2024-06-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (160, '크로켓', '물냉면', '해물탕', '2024-06-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (161, '오야코동', '갈릭 새우 파스타', '보리밥', '2024-06-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (162, '푸실리 파스타', '가자미조림', '탕수육', '2024-06-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (163, '토마토 치즈 타르트', '북경오리', '마라샹궈', '2024-06-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (164, '마르게리타 피자', '소곱창', '항정살', '2024-06-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (165, '브로콜리 샐러드', '사골국', '트러플 감자튀김', '2024-06-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (166, '트로피컬 샐러드', '타마고야키', '마파두부', '2024-06-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (167, '돈가스 김밥', '렌틸콩 샐러드', '곱창전골', '2024-06-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (168, '유린기', '유부 김밥', '베이컨 김밥', '2024-06-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (169, '돼지고기볶음', '마파면', '오삼불고기', '2024-06-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (170, '시래기된장국', '랍스터 크림 스프', '햄버거', '2024-06-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (171, '닭갈비 덮밥', '설렁탕', '멘보샤', '2024-06-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (172, '양송이 크림파스타', '돼지고기볶음', '명란 크림파스타', '2024-06-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (173, '소룡포', '쉬림프 타코', '새우 크림 리조또', '2024-06-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (174, '참치국', '쭈꾸미볶음', '라임 치킨', '2024-06-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (175, '토마토 달걀 볶음', '김치볶음밥', '콩나물국', '2024-06-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (176, '제육볶음', '조개찜', '가츠동', '2024-06-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (177, '설렁탕', '연어 스테이크', '짬뽕', '2024-06-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (178, '짜장밥', '라임 치킨', '갈치조림', '2024-06-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (179, '소고기덮밥', '샤케동', '렌틸콩 샐러드', '2024-06-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (180, '가자미조림', '파파야 샐러드', '순두부국', '2024-06-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (181, '베이컨 김밥', '스테이크', '브런치 세트', '2024-06-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (182, '참치 니스와 샐러드', '소막창', '잡채', '2024-06-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (183, '삼계탕', '레몬 버터 새우', '마파두부밥', '2024-07-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (184, '애호박전', '오니기리', '감자크림수프', '2024-07-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (185, '짜장밥', '고추짬뽕', '살사 치킨 타코', '2024-07-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (186, '레몬 치킨', '규카츠 덮밥', '사우전 아일랜드 샐러드', '2024-07-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (187, '유산슬', '임연수구이', '훈툰', '2024-07-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (188, '카마메시', '양고기 찹스', '덴푸라', '2024-07-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (189, '김치볶음밥', '구운 감자 샐러드', '프레즐', '2024-07-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (190, '사우전 아일랜드 샐러드', '멘보샤', '라따뚜이', '2024-07-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (191, '오코노미야키', '참치 니스와 샐러드', '쉬림프 타코', '2024-07-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (192, '짬짜면', '야채 김밥', '트로피컬 샐러드', '2024-07-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (193, '양고기 찹스', '마파두부밥', '무채 비빔국수', '2024-07-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (194, '삼합', '피쉬 앤 칩스', '우동', '2024-07-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (195, '육회', '꽃목살', '꽁치구이', '2024-07-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (196, '가츠샌드', '낙지탕탕이', '소대창', '2024-07-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (197, '불닭', '시금치 수프', '바질 페스토 샌드위치', '2024-07-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (198, '명태구이', '양고기 찹스', '야끼소바', '2024-07-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (199, '굴밥', '고등어구이', '에그 베네딕트', '2024-07-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (200, '돼지갈비', '야끼소바', '비트 수프', '2024-07-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (201, '트로피컬 샐러드', '바베큐 치킨', '새우가츠동', '2024-07-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (202, '계란 김밥', '오코노미야키', '와플 샌드위치', '2024-07-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (203, '새우구이', '김치국', '비건 버거', '2024-07-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (204, '갈치구이', '배추국', '팥죽', '2024-07-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (205, '칼국수', '오징어순대', '베이컨 감자 샐러드', '2024-07-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (206, '마라탕', '낙지탕탕이', '시금치 피자', '2024-07-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (207, '오향장육', '차슈 라멘', '된장찌개', '2024-07-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (208, '라임 치킨', '참치 니스와 샐러드', '파삼겹', '2024-07-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (209, '크림치즈 베이글', '바베큐 치킨', '아란치니', '2024-07-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (210, '가이센동', '크림 바질 피자', '라따뚜이', '2024-07-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (211, '월남쌈', '닭가슴살 튀김', '상하이볶음면', '2024-07-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (212, '삼선짬뽕밥', '닭볶음탕', '타코', '2024-07-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (213, '돈카츠 회오리 오므라이스', '명태구이', '김치볶음밥', '2024-07-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (214, '탄탄멘', '멘보샤', '가이센동', '2024-08-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (215, '장어구이', '돼지고기볶음', '피자 토스트', '2024-08-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (216, '한치물회', '부대찌개', '월남쌈', '2024-08-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (217, '불닭볶음면', '바질 파스타', '참치 샌드위치', '2024-08-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (218, '연어 스테이크', '감자크림수프', '고추기름 닭고기', '2024-08-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (219, '파스타', '아란치니', '까르보나라 불닭볶음면', '2024-08-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (220, '광어 사시미', '미소 된장국', '갈릭 토스트', '2024-08-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (221, '토마토 달걀 볶음', '된장찌개', '김치국', '2024-08-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (222, '마파면', '새우 토스트', '초계비빔국수', '2024-08-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (223, '콩나물국', '오차즈케', '돼지갈비', '2024-08-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (224, '소바', '치즈 감자튀김', '우거지국', '2024-08-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (225, '베이글 샌드위치', '파삼겹', '오차즈케', '2024-08-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (226, '낙지국', '낙지탕탕이', '연어구이', '2024-08-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (227, '시금치 수프', '비프 타르타르', '타코야키', '2024-08-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (228, '고등어조림', '소룡포', '고구마튀김', '2024-08-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (229, '양고기 스테이크', '하이라이스', '물막국수', '2024-08-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (230, '고구마튀김', '푸실리 파스타', '에비텐동', '2024-08-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (231, '브로콜리 체다 수프', '양꼬치', '치킨 알프레도', '2024-08-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (232, '연어 김밥', '레몬 버터 새우', '클럽 샌드위치', '2024-08-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (233, '초벌 막창', '시저 파스타 샐러드', '시나몬 롤', '2024-08-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (234, '닭강정', '토마토 치즈 타르트', '사천식 양꼬치', '2024-08-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (235, '연어 김밥', '떡볶이', '낙지볶음', '2024-08-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (236, '계란국', '호박죽', '타이 그린 카레', '2024-08-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (237, '감바스 알 아히요', '사천식 양꼬치', '프레즐', '2024-08-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (238, '치즈계란말이', '양꼬치', '크로크무슈', '2024-08-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (239, '닭가슴살 스테이크', '고추장찌개', '마라탕', '2024-08-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (240, '치킨 파마산', '바질 파스타', '갈치구이', '2024-08-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (241, '마라샹궈', '쌀국수', '덴푸라', '2024-08-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (242, '버섯 리소토', '버팔로 치킨 샌드위치', '돼지고기묵은지찜', '2024-08-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (243, '포테이토 샐러드', '체다 치즈 튀김', '단호박튀김', '2024-08-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (244, '시금치 수프', '허니 버터 칩', '만두국', '2024-08-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (245, '오차즈케', '소갈비살', '보리밥', '2024-09-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (246, '베이글 샌드위치', '감바스 리조또', '잔치국수', '2024-09-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (247, '도미구이', '라자냐', '소대창', '2024-09-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (248, '비트 수프', '시래기된장국', '브루스케타', '2024-09-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (249, '보리밥', '새우완자', '설렁탕', '2024-09-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (250, '전주비빔밥', '호박 수프', '우거지국', '2024-09-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (251, '제육덮밥', '돼지고기묵은지찜', '소룡포', '2024-09-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (252, '포테이토베이컨 피자', '고추참치 김밥', '와플 샌드위치', '2024-09-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (253, '우렁 된장찌개', '타코', '시나몬 롤', '2024-09-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (254, '꿔바로우 샐러드', '베이컨 김밥', '수박 샐러드', '2024-09-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (255, '삼겹살', '새우튀김', '물냉면', '2024-09-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (256, '해물탕', '닭갈비 덮밥', '부타동', '2024-09-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (257, '새우 스캄피 파스타', '중화비빔면', '햄버거', '2024-09-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (258, '감자그라탕', '연어 스테이크', '블랙빈 수프', '2024-09-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (259, '베이컨 에그 베네딕트', '꽁치조림', '멘보샤', '2024-09-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (260, '갈비탕', '메밀국수 샐러드', '닭가슴살 튀김', '2024-09-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (261, '마파면', '유산슬', '블랙 올리브 파스타', '2024-09-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (262, '랍스터 롤', '소룡포', '토마토 모차렐라 피자', '2024-09-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (263, '유부 김밥', '짬뽕', '교카이라멘', '2024-09-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (264, '마늘빵', '맥 앤 치즈', '까르보나라 파스타', '2024-09-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (265, '랍스터 비스크', '미트볼 파스타', '디아블로 피자', '2024-09-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (266, '마라양념탕수육', '참치 샌드위치', '토마호크 스테이크', '2024-09-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (267, '샐러드 피자', '미소 된장국', '가라아게가츠동', '2024-09-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (268, '설렁탕', '방어구이', '스윗 칠리 새우', '2024-09-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (269, '감자찌개', '참치 니스와 샐러드', '베이컨 에그 베네딕트', '2024-09-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (270, '트러플 리소토', '돈카츠 회오리 오므라이스', '삼합', '2024-09-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (271, '참치 샌드위치', '멘보샤', '바질 페스토 샌드위치', '2024-09-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (272, '오렌지 치킨', '상하이볶음면', '소곱창', '2024-09-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (273, '우렁강된장', '연어구이', '계란국', '2024-09-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (274, '동태찌개', '연어 사시미', '코코넛 치킨', '2024-09-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (275, '찐빵', '고구마치즈카츠', '유부 김밥', '2024-10-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (276, '잔치국수', '리조또', '마라탕', '2024-10-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (277, '파전', '깐쇼새우덮밥', '베지터블 라자냐', '2024-10-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (278, '초계비빔국수', '닭다리 구이', '규동', '2024-10-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (279, '참치 김밥', '제육볶음', '새우 김밥', '2024-10-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (280, '우렁 된장찌개', '클럽 샌드위치', '마파면', '2024-10-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (281, '마라짬뽕', '불고기 덮밥', '햄버거', '2024-10-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (282, '초밥', '회냉면', '해물된장찌개', '2024-10-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (283, '바지락 칼국수', '두부김치', '순두부찌개', '2024-10-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (284, '돈부리', '쭈꾸미볶음', '푸아그라', '2024-10-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (285, '순대국', '깐쇼새우덮밥', '살몬 아보카도 샐러드', '2024-10-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (286, '감자그라탕', '바질소바', '매콤로제파스타', '2024-10-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (287, '불고기', '포테이토베이컨 피자', '훈툰', '2024-10-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (288, '홍합찜', '소바', '치킨 크림파스타', '2024-10-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (289, '버섯 볶음밥', '고추기름 닭고기', '토마토 수프', '2024-10-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (290, '열무김치', '매운돼지갈비', '타마고야키', '2024-10-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (291, '항정살', '튀김우동', '닭강정', '2024-10-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (292, '갈비구이', '비빔국수', '장어정식', '2024-10-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (293, '교카이라멘', '황태국', '참치 김밥', '2024-10-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (294, '갈비구이', '시저 파스타 샐러드', '전주비빔밥', '2024-10-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (295, '탕수육', '샤케동', '알리오 올리오', '2024-10-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (296, '니쿠자가', '브로콜리 체다 수프', '꼬막비빔밥', '2024-10-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (297, '버팔로 치킨 샌드위치', '연어 샌드위치', '물냉면', '2024-10-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (298, '퀘사디아', '시금치 수프', '오리 로스트', '2024-10-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (299, '떡국', '단호박튀김', '할라피뇨 팝퍼', '2024-10-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (300, '김치볶음면', '황태찌개', '백숙', '2024-10-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (301, '오니기리', '고등어구이', '조개찜', '2024-10-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (302, '배추국', '피쉬 앤 칩스', '브루스케타', '2024-10-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (303, '소시지 그라탱', '해물찜', '샐러드롤', '2024-10-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (304, '오차즈케', '시메사바', '연어구이', '2024-10-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (305, '타이 그린 카레', '오렌지 치킨', '튀김우동', '2024-10-31');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (306, '치킨 필라프', '불고기 타코', '코코넛 치킨', '2024-11-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (307, '콩국수', '떡국', '규동', '2024-11-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (308, '숙성지 김치찌개', '체다 감자 크림', '파김치장어전골', '2024-11-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (309, '유부 초밥', '치킨 시저랩', '부추전', '2024-11-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (310, '날치알 주먹밥', '보리밥', '새우 토스트', '2024-11-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (311, '토마토 수프', '양송이 크림파스타', '홍합찜', '2024-11-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (312, '고구마전', '부추전', '잔치국수', '2024-11-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (313, '고등어조림', '치킨 시저랩', '소바', '2024-11-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (314, '샐러드롤', '살몬 크림 파스타', '라따뚜이', '2024-11-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (315, '연어 타르타르', '돈카츠 회오리 오므라이스', '돼지갈비', '2024-11-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (316, '부추전', '미트볼 파스타', '바질페스토 피자', '2024-11-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (317, '북경오리', '차돌박이 된장찌개', '떡국', '2024-11-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (318, '연어 김밥', '체다 감자 크림', '꽁치조림', '2024-11-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (319, '굴전', '해물라면', '유부 김밥', '2024-11-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (320, '파전', '메밀국수 샐러드', '훈툰', '2024-11-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (321, '김치볶음면', '미트볼 파스타', '오야코동', '2024-11-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (322, '아귀찜', '치킨 팟파이', '삼합', '2024-11-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (323, '삼계탕', '시래기된장국', '삼겹살', '2024-11-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (324, '토마토 바질 스프', '사천식 양꼬치', '감자 샐러드', '2024-11-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (325, '우동', '감자찌개', '칠리 치즈 감자튀김', '2024-11-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (326, '파스타', '버팔로윙', '사골국', '2024-11-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (327, '맥 앤 치즈', '미소 된장국', '햄 치즈 토스트', '2024-11-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (328, '쉬림프 타코', '시나몬 롤', '크림수프', '2024-11-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (329, '무국', '사골국', '고구마치즈카츠', '2024-11-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (330, '치킨 파마산', '포크 롤', '마라탕', '2024-11-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (331, '토마토 모차렐라 피자', '치킨 시저랩', '새우튀김', '2024-11-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (332, '월남쌈', '리조또', '보쌈', '2024-11-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (333, '시저 샐러드', '크림치즈 파스타', '라멘', '2024-11-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (334, '토마토 모차렐라 피자', '유부 초밥', '파삼겹', '2024-11-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (335, '임연수구이', '두부전골', '잡채밥', '2024-11-30');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (336, '브로콜리 샐러드', '할라피뇨 팝퍼', '규카츠', '2024-12-01');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (337, '닭가슴살 스테이크', '새우 토스트', '오야코동', '2024-12-02');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (338, '떡국', '타이 새우 볶음', '애호박찌개', '2024-12-03');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (339, '두부조림', '콩나물국', '참치 카나페', '2024-12-04');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (340, '닭볶음탕', '로스카츠', '야채튀김', '2024-12-05');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (341, '규카츠', '타이 새우 볶음', '햄 치즈 파니니', '2024-12-06');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (342, '청포묵', '브루스케타', '돼지갈비 스튜', '2024-12-07');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (343, '치즈 감자튀김', '매운 갈비찜 찌개', '비트 샐러드', '2024-12-08');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (344, '크림 바질 피자', '차슈 라멘', '고추기름 닭고기', '2024-12-09');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (345, '매콤로제파스타', '낙지볶음', '마파두부', '2024-12-10');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (346, '부리또', '닭튀김', '쫄면', '2024-12-11');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (347, '오코노미야키', '깐풍기', '시메사바', '2024-12-12');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (348, '시래기된장국', '동태찌개', '미트로프', '2024-12-13');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (349, '카마메시', '애호박전', '호박 수프', '2024-12-14');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (350, '소룡포', '오삼불고기', '코코넛 치킨', '2024-12-15');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (351, '치즈계란말이', '치즈 감자튀김', '햄 치즈 파니니', '2024-12-16');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (352, '회냉면', '굴전', '트러플 파스타', '2024-12-17');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (353, '마파두부', '한치물회', '크로크무슈', '2024-12-18');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (354, '배추국', '브로콜리 체다 수프', '날치알 김밥', '2024-12-19');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (355, '탕수육', '마늘빵', '쌀국수', '2024-12-20');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (356, '김치전', '참치 샌드위치', '명란 크림파스타', '2024-12-21');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (357, '체다 감자 크림', '갈릭 토스트', '랍스터 비스크', '2024-12-22');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (358, '베이컨 에그 베네딕트', '햄버거', '연어 사시미', '2024-12-23');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (359, '바질페스토 피자', '호박전', '토마토 치즈 타르트', '2024-12-24');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (360, '까르보나라 파스타', '닭강정', '라조기', '2024-12-25');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (361, '콩국수', '유산슬', '초계국수', '2024-12-26');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (362, '크림치즈 파스타', '클램 차우더', '장어구이', '2024-12-27');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (363, '규카츠 덮밥', '알리오 올리오', '토마토 갈릭 파스타', '2024-12-28');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (364, '살몬 크림 파스타', '홍합탕', '황태찌개', '2024-12-29');
INSERT INTO meal (id, breakfast, lunch, dinner, meal_date) VALUES (365, '우렁강된장', '후라이드 치킨', '감자 피자', '2024-12-30');
